name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Change this if you use a different Node version

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10 # Change this if you use a different pnpm version

      - name: Build the Client
        run: |
          cd client
          pnpm install
          pnpm run build

      - name: Create .env file for Server
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.PORT }}
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          EOF

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          # Exclude git, and DO NOT sync node_modules (explained below)
          switches: -avz --delete --exclude='.git/' --exclude='client/node_modules/' --exclude='node_modules/'
          path: ./
          remote_path: /var/www/issa-beauty/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Server dependencies and Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/issa-beauty

            # Install only backend dependencies on the actual server
            /root/.local/share/pnpm/pnpm install --prod

            # Restart or start PM2
            pm2 restart issa-beauty --update-env || NODE_ENV=production pm2 start server/index.js --name "issa-beauty"
